/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies/index'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as EnAboutRouteImport } from './routes/en/about'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies/$slug'
import { Route as EnServicesIndexRouteImport } from './routes/en/services/index'
import { Route as EnCaseStudiesIndexRouteImport } from './routes/en/case-studies/index'
import { Route as EnServicesSlugRouteImport } from './routes/en/services/$slug'
import { Route as EnCaseStudiesSlugRouteImport } from './routes/en/case-studies/$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutRoute = EnAboutRouteImport.update({
  id: '/en/about',
  path: '/en/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/case-studies/$slug',
  path: '/case-studies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnServicesIndexRoute = EnServicesIndexRouteImport.update({
  id: '/en/services/',
  path: '/en/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnCaseStudiesIndexRoute = EnCaseStudiesIndexRouteImport.update({
  id: '/en/case-studies/',
  path: '/en/case-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnServicesSlugRoute = EnServicesSlugRouteImport.update({
  id: '/en/services/$slug',
  path: '/en/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EnCaseStudiesSlugRoute = EnCaseStudiesSlugRouteImport.update({
  id: '/en/case-studies/$slug',
  path: '/en/case-studies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/en/about': typeof EnAboutRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/en/': typeof EnIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/en/case-studies/$slug': typeof EnCaseStudiesSlugRoute
  '/en/services/$slug': typeof EnServicesSlugRoute
  '/en/case-studies/': typeof EnCaseStudiesIndexRoute
  '/en/services/': typeof EnServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/en/about': typeof EnAboutRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/case-studies': typeof CaseStudiesIndexRoute
  '/en': typeof EnIndexRoute
  '/services': typeof ServicesIndexRoute
  '/en/case-studies/$slug': typeof EnCaseStudiesSlugRoute
  '/en/services/$slug': typeof EnServicesSlugRoute
  '/en/case-studies': typeof EnCaseStudiesIndexRoute
  '/en/services': typeof EnServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/en/about': typeof EnAboutRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
  '/en/': typeof EnIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/en/case-studies/$slug': typeof EnCaseStudiesSlugRoute
  '/en/services/$slug': typeof EnServicesSlugRoute
  '/en/case-studies/': typeof EnCaseStudiesIndexRoute
  '/en/services/': typeof EnServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/case-studies/$slug'
    | '/en/about'
    | '/services/$slug'
    | '/case-studies/'
    | '/en/'
    | '/services/'
    | '/en/case-studies/$slug'
    | '/en/services/$slug'
    | '/en/case-studies/'
    | '/en/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/case-studies/$slug'
    | '/en/about'
    | '/services/$slug'
    | '/case-studies'
    | '/en'
    | '/services'
    | '/en/case-studies/$slug'
    | '/en/services/$slug'
    | '/en/case-studies'
    | '/en/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sitemap.xml'
    | '/case-studies/$slug'
    | '/en/about'
    | '/services/$slug'
    | '/case-studies/'
    | '/en/'
    | '/services/'
    | '/en/case-studies/$slug'
    | '/en/services/$slug'
    | '/en/case-studies/'
    | '/en/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
  EnAboutRoute: typeof EnAboutRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
  EnIndexRoute: typeof EnIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  EnCaseStudiesSlugRoute: typeof EnCaseStudiesSlugRoute
  EnServicesSlugRoute: typeof EnServicesSlugRoute
  EnCaseStudiesIndexRoute: typeof EnCaseStudiesIndexRoute
  EnServicesIndexRoute: typeof EnServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about': {
      id: '/en/about'
      path: '/en/about'
      fullPath: '/en/about'
      preLoaderRoute: typeof EnAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/case-studies/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/services/': {
      id: '/en/services/'
      path: '/en/services'
      fullPath: '/en/services/'
      preLoaderRoute: typeof EnServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/case-studies/': {
      id: '/en/case-studies/'
      path: '/en/case-studies'
      fullPath: '/en/case-studies/'
      preLoaderRoute: typeof EnCaseStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/services/$slug': {
      id: '/en/services/$slug'
      path: '/en/services/$slug'
      fullPath: '/en/services/$slug'
      preLoaderRoute: typeof EnServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/case-studies/$slug': {
      id: '/en/case-studies/$slug'
      path: '/en/case-studies/$slug'
      fullPath: '/en/case-studies/$slug'
      preLoaderRoute: typeof EnCaseStudiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
  EnAboutRoute: EnAboutRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
  EnIndexRoute: EnIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  EnCaseStudiesSlugRoute: EnCaseStudiesSlugRoute,
  EnServicesSlugRoute: EnServicesSlugRoute,
  EnCaseStudiesIndexRoute: EnCaseStudiesIndexRoute,
  EnServicesIndexRoute: EnServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
